[{"id":"dsq-457710897","author":"Roman Shtylman","deleted":false,"createdAt":"2009-12-22T22:16:23Z","message":"<p>I did something similar when debugging an OpenOffice kde4 bug a while back. I always seem to forget that you can set breakpoints on function calls and constructors. It comes it very handy :)</p>","replies":[]},{"id":"dsq-457710899","author":"Esben Mose Hansen","deleted":false,"createdAt":"2009-12-23T02:13:34Z","message":"<p>catch throw</p><p>catch catch</p><p>Those two every C++ programmer should know. The first one breaks when an exception is thrown, the second when it is caught. Very useful stuff.</p>","replies":[{"id":"dsq-457712212","author":"Aur√©lien","deleted":false,"createdAt":"2009-12-23T03:00:02Z","message":"<p>Nice!</p><p>Once again, posting tips on a blog proves to be a great way to learn better tips!</p>","replies":[]}]},{"id":"dsq-457710894","author":"Frank Osterfeld","deleted":false,"createdAt":"2009-12-23T02:15:43Z","message":"<p>Or use Catchpoints: \"catch throw\" for breaking at any throw, or \"catch catch\" to break on catch.</p>","replies":[]}]
